Add configuration statements to explicitly configure the FEA interfaces.
git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@3734 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/mld6igmp/configure_mld6igmp b/trunk/xorp/mld6igmp/configure_mld6igmp
--- a/trunk/xorp/mld6igmp/configure_mld6igmp
+++ b/trunk/xorp/mld6igmp/configure_mld6igmp
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #
-# $XORP: xorp/mld6igmp/configure_mld6igmp,v 1.16 2003/12/20 01:43:34 pavlin Exp $
+# $XORP: xorp/mld6igmp/configure_mld6igmp,v 1.17 2004/02/26 08:49:02 pavlin Exp $
 #
 
 #
@@ -121,6 +121,7 @@ CLI_DISABLE_SUBNETS="0.0.0.0/0"		# Disable everything else
 # Read-in the files with helper functions
 #
 . ${srcdir}/../cli/xrl_cli_shell_funcs.sh
+. ${srcdir}/../fea/xrl_fea_shell_funcs.sh
 . ${srcdir}/../fea/xrl_mfea_shell_funcs.sh
 . ${srcdir}/../mld6igmp/xrl_mld6igmp_shell_funcs.sh
 
@@ -161,6 +162,19 @@ done
 #
 cli_enable_cli true
 cli_start_cli
+
+#
+# Configure FEA interfaces
+#
+tid=`get_xrl_variable_value \`fea_ifmgr_start_transaction\` tid:u32`
+if [ "${tid}" = "" ] ; then
+	echo "ERROR: cannot start transaction: cannot get transaction ID"
+	exit 1
+fi
+for vif in ${ENABLE_VIFS}; do
+	fea_ifmgr_configure_interface_from_system ${tid} ${vif}
+done
+fea_ifmgr_commit_transaction ${tid}
 
 #
 # Enable and start MFEA CLI
diff --git a/trunk/xorp/pim/configure_pim b/trunk/xorp/pim/configure_pim
--- a/trunk/xorp/pim/configure_pim
+++ b/trunk/xorp/pim/configure_pim
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #
-# $XORP: xorp/pim/configure_pim,v 1.30 2004/03/02 00:32:32 pavlin Exp $
+# $XORP: xorp/pim/configure_pim,v 1.31 2004/03/05 03:44:10 pavlin Exp $
 #
 
 #
@@ -240,6 +240,7 @@ PIM_SWITCH_TO_SPT_THRESHOLD_BYTES=102400
 # Read-in the files with helper functions
 #
 . ${srcdir}/../cli/xrl_cli_shell_funcs.sh
+. ${srcdir}/../fea/xrl_fea_shell_funcs.sh
 . ${srcdir}/../fea/xrl_mfea_shell_funcs.sh
 . ${srcdir}/../mld6igmp/xrl_mld6igmp_shell_funcs.sh
 . ${srcdir}/../pim/xrl_rib_shell_funcs.sh
@@ -288,6 +289,19 @@ done
 #
 cli_enable_cli true
 cli_start_cli
+
+#
+# Configure FEA interfaces
+#
+tid=`get_xrl_variable_value \`fea_ifmgr_start_transaction\` tid:u32`
+if [ "${tid}" = "" ] ; then
+	echo "ERROR: cannot start transaction: cannot get transaction ID"
+	exit 1
+fi
+for vif in ${ENABLE_VIFS}; do
+	fea_ifmgr_configure_interface_from_system ${tid} ${vif}
+done
+fea_ifmgr_commit_transaction ${tid}
 
 #
 # Enable and start MFEA CLI
