Explicitly add the "-g" gcc compilation flag to CFLAGS and CXXFLAGS when debugging is enabled instead of relying of it being added implicitly by macro AC_PROG_CC and AC_PROG_CXX.
Approved by:	Atanu


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@4916 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -9702,6 +9702,170 @@ fi
 
 
 if test "${GCC}" = "yes" ; then
+				CFLAGS=`echo $CFLAGS |  sed 's/-g//g'`
+	CXXFLAGS=`echo $CXXFLAGS |  sed 's/-g//g'`
+
+				if test "${enable_debug}" = "yes" ; then
+		for ac_flag in "-g"
+  do
+      ac_safe=`echo "$ac_flag" | sed 'y%./+- %__p__%'`
+
+
+  _save_flags="$CFLAGS"
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  CFLAGS="$CFLAGS $ac_flag"
+  echo "$as_me:$LINENO: checking whether C compiler supports flag \"$ac_flag\"" >&5
+echo $ECHO_N "checking whether C compiler supports flag \"$ac_flag\"... $ECHO_C" >&6
+  if eval "test \"\${ac_cv_prog_c_compiler_$ac_safe+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+return (0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "ac_cv_prog_c_compiler_$ac_safe=yes"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "ac_cv_prog_c_compiler_$ac_safe=no"
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+  CFLAGS="$_save_flags"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if eval "test \"`echo '$ac_cv_prog_c_compiler_'$ac_safe`\" = yes"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    CFLAGS="$CFLAGS $ac_flag"
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+  fi
+
+  done
+
+		for ac_flag in "-g"
+  do
+      ac_safe=`echo "$ac_flag" | sed 'y%./+- %__p__%'`
+
+
+  _save_flags="$CXXFLAGS"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  CXXFLAGS="$CXXFLAGS $ac_flag"
+  echo "$as_me:$LINENO: checking whether C++ compiler supports flag \"$ac_flag\"" >&5
+echo $ECHO_N "checking whether C++ compiler supports flag \"$ac_flag\"... $ECHO_C" >&6
+  if eval "test \"\${ac_cv_prog_cxx_compiler_$ac_safe+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+return (0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "ac_cv_prog_cxx_compiler_$ac_safe=yes"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "ac_cv_prog_cxx_compiler_$ac_safe=no"
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+  CXXFLAGS="$_save_flags"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if eval "test \"`echo '$ac_cv_prog_cxx_compiler_'$ac_safe`\" = yes"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    CXXFLAGS="$CXXFLAGS $ac_flag"
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+  fi
+
+  done
+
+	fi
+
 															CPARANOIDFLAGS="-W -Wall -Wwrite-strings -Wbad-function-cast -Wmissing-prototypes -Wcast-qual -Wmissing-declarations -Werror -Wpointer-arith -Wcast-align -Wstrict-prototypes -Wnested-externs"
 	CXXPARANOIDFLAGS="-W -Wall -Wwrite-strings -Wcast-qual -Werror -Wpointer-arith -Wcast-align -Wstrict-prototypes -Woverloaded-virtual -Wtraditional"
 	for ac_flag in $CPARANOIDFLAGS
@@ -10101,12 +10265,7 @@ echo "${ECHO_T}no" >&6
   done
 
 
-				if test "${enable_debug}" = "no" ; then
-		CFLAGS=`echo $CFLAGS |  sed 's/-g//g'`
-		CXXFLAGS=`echo $CXXFLAGS |  sed 's/-g//g'`
-	fi
-
-			if test "${enable_optimize}" != "yes" ; then
+					if test "${enable_optimize}" != "yes" ; then
 										CFLAGS=`echo $CFLAGS | sed 's/-O2//g'`
 		CXXFLAGS=`echo $CXXFLAGS | sed 's/-O2//g'`
 			fi
