Refactor the code for testing whether the system supports IPv6 multicast routing. Now we conditionally include <net/if_var.h> and <netinet/in_var.h>, because those files may not be available (e.g., NetBSD doesn't have <net/if_var.h>, and Linux doesn't have both).
git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@2379 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -7777,20 +7777,241 @@ echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 
+if test "${ac_cv_header_net_if_var_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for net/if_var.h" >&5
+echo $ECHO_N "checking for net/if_var.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_if_var_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_if_var_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_if_var_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking net/if_var.h usability" >&5
+echo $ECHO_N "checking net/if_var.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <net/if_var.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking net/if_var.h presence" >&5
+echo $ECHO_N "checking net/if_var.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <net/if_var.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: net/if_var.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: net/if_var.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: net/if_var.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for net/if_var.h" >&5
+echo $ECHO_N "checking for net/if_var.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_if_var_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_net_if_var_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_if_var_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_if_var_h" >&6
+
+fi
+if test $ac_cv_header_net_if_var_h = yes; then
+  test_net_if_var_h="#include <net/if_var.h>"
+else
+  test_net_if_var_h=""
+fi
+
+
+if test "${ac_cv_header_netinet_in_var_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for netinet/in_var.h" >&5
+echo $ECHO_N "checking for netinet/in_var.h... $ECHO_C" >&6
+if test "${ac_cv_header_netinet_in_var_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_netinet_in_var_h" >&5
+echo "${ECHO_T}$ac_cv_header_netinet_in_var_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking netinet/in_var.h usability" >&5
+echo $ECHO_N "checking netinet/in_var.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <netinet/in_var.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking netinet/in_var.h presence" >&5
+echo $ECHO_N "checking netinet/in_var.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <netinet/in_var.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: netinet/in_var.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: netinet/in_var.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netinet/in_var.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: netinet/in_var.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: netinet/in_var.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: netinet/in_var.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netinet/in_var.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: netinet/in_var.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netinet/in_var.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: netinet/in_var.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for netinet/in_var.h" >&5
+echo $ECHO_N "checking for netinet/in_var.h... $ECHO_C" >&6
+if test "${ac_cv_header_netinet_in_var_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_netinet_in_var_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_netinet_in_var_h" >&5
+echo "${ECHO_T}$ac_cv_header_netinet_in_var_h" >&6
+
+fi
+if test $ac_cv_header_netinet_in_var_h = yes; then
+  test_netinet_in_var_h="#include <netinet/in_var.h>"
+else
+  test_netinet_in_var_h=""
+fi
+
+
+
+test_multicast_routing_header_files="
+#include <sys/types.h>
+#include <sys/param.h>
+#include <sys/socket.h>
+#include <net/if.h>
+${test_net_if_var_h}
+#include <netinet/in.h>
+${test_netinet_in_var_h}
+#include <netinet6/ip6_mroute.h>
+"
+
 echo "$as_me:$LINENO: checking whether the system IPv6 stack supports IPv6 multicast routing" >&5
 echo $ECHO_N "checking whether the system IPv6 stack supports IPv6 multicast routing... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
-#include <sys/types.h>
-#include <sys/param.h>
-#include <sys/socket.h>
-#include <net/if.h>
-#include <net/if_var.h>
-#include <netinet/in.h>
-#include <netinet/in_var.h>
-#include <netinet6/ip6_mroute.h>
+${test_multicast_routing_header_files}
 
 #ifdef F77_DUMMY_MAIN
 #  ifdef __cplusplus
@@ -7804,7 +8025,7 @@ main ()
 
 int dummy = 0;
 
-/* Dummy values that must be defined in some of the header files */
+/* Dummy integer values that must be defined in some of the header files */
 dummy += IPPROTO_ICMPV6;
 dummy += MRT6_INIT;
 dummy += MRT6_ADD_MIF;
@@ -7816,10 +8037,10 @@ dummy += MRT6MSG_WRONGMIF;
 dummy += MRT6MSG_WHOLEPKT;
 
 #ifndef SIOCGETSGCNT_IN6
-#error "Missing SIOCGETSGCNT_IN6"
+#error Missing SIOCGETSGCNT_IN6
 #endif
 #ifndef SIOCGETMIFCNT_IN6
-#error "Missing SIOCGETMIFCNT_IN6"
+#error Missing SIOCGETMIFCNT_IN6
 #endif
 
   ;
