* If the snmpd revision number is missing, then give it value of 0   This fixes the test-case when the snmpd version is, say, 5.1   instead of 5.1.0
* Fix the logic for testing whether the snmpd version is >= 5.0.6

* Use a separate variable snmpd_flags_valid to test whether the
  snmpd compilation flags are valid.

* Check whether header file <net-snmp/agent/net-snmp-agent-includes.h>
  is usable. It appears that in case of net-snmp version 5.1 (and later?)
  we cannot include the following three files and compile them with g++ :
  #include <net-snmp/net-snmp-config.h>
  #include <net-snmp/net-snmp-includes.h>
  #include <net-snmp/agent/net-snmp-agent-includes.h>

  The reason appears to be a bug in the net-snmp-agent-includes.h
  header file (it can be compiled with gcc, but it cannot be compiled
  with g++).

* Remove the warning that we need to patch file
  <net-snmp/library/container.h>, because it may be printed even if
  the problem is elsewhere. Further, it appears that the problem
  has been fixed in recent net-snmp releases.

* If neither <net-snmp/agent/net-snmp-agent-includes.h> nor
  <net-snmp/library/container.h> is usable, then do not
  compile MIBS.
  We may try to fix net-snmp-agent-includes.h locally (similar to the
  local fix of container.h), but this is an error-prone solution.


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@3469 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -4256,18 +4256,18 @@ if test "${net_snmp_found}" = "true";  then
     net_snmp_maj=`echo $net_snmp_v | cut -f 1 -d.`
     net_snmp_min=`echo $net_snmp_v | cut -f 2 -d.`
     net_snmp_rev=`echo $net_snmp_v | cut -f 3 -d.`
+                if test "${net_snmp_rev}" = ""; then
+	net_snmp_rev=0
+    fi
+    net_snmp_unified_ver=$(($net_snmp_maj*100+$net_snmp_min*10+$net_snmp_rev))
     echo "$as_me:$LINENO: checking if net-snmp version equal or newer than 5.0.6" >&5
 echo $ECHO_N "checking if net-snmp version equal or newer than 5.0.6... $ECHO_C" >&6
 if test "${ac_cv_net_snmp_usable+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  net_snmp_too_old=false
-	if test "5" -gt $net_snmp_maj ; then
-	    net_snmp_too_old=true
-	elif test "0" -gt $net_snmp_min ; then
-	    net_snmp_too_old=true
-	elif test "6" -gt $net_snmp_rev ; then
-	    net_snmp_too_old=true
+  net_snmp_too_old=true
+	if test "${net_snmp_unified_ver}" -ge "506" ; then
+	    net_snmp_too_old=false
 	fi
 	if test "${net_snmp_too_old}" != "true"; then
 	    ac_cv_net_snmp_usable=yes
@@ -4446,6 +4446,7 @@ echo "${ECHO_T}no" >&6
     fi
 fi
 
+oldCPPFLAGS=${CPPFLAGS}
 while test "${net_snmp_found}" = "true"; do
     NETSNMPCFLAGS=`net-snmp-config --cflags`
     # Darwin 7.0.0 / OS X 10.3 on ppc gives ppc and i386 arch flags which
@@ -4518,22 +4519,81 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
   if eval "test \"`echo '$ac_cv_prog_c_compiler_'$ac_safe`\" = yes"; then
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    :
+    snmpd_flags_valid=yes
   else
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-    snmpd_valid=no
+    snmpd_flags_valid=no
   fi
 
-    if test "${snmpd_valid}" = "no" ; then
+    if test "${snmpd_flags_valid}" = "no" ; then
 	echo "-------------------------------------------------------------   "
-	echo "'net-snmp-config --cflags' gave invalid invalid cflags!         "
+	echo "'net-snmp-config --cflags' gave invalid cflags!                 "
 	echo "-------------------------------------------------------------   "
+	snmpd_valid=no
 	break
     fi
 
-    oldCPPFLAGS=${CPPFLAGS}
     CPPFLAGS=${NETSNMPCFLAGS}
+
+for ac_header in net-snmp/agent/net-snmp-agent-includes.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+        #include <net-snmp/net-snmp-config.h>
+        #include <net-snmp/net-snmp-includes.h>
+
+
+
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_Header=no"
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ net_snmp_agent_includes_bug=no
+else
+  net_snmp_agent_includes_bug=yes
+fi
+
+done
+
+    if test "${net_snmp_agent_includes_bug}" = "yes" ; then
+	{ echo "$as_me:$LINENO: WARNING: File <net-snmp/agent/net-snmp-agent-includes.h> does not appear usable" >&5
+echo "$as_me: WARNING: File <net-snmp/agent/net-snmp-agent-includes.h> does not appear usable" >&2;}
+	snmpd_valid=no
+	break
+    fi
 
 for ac_header in net-snmp/library/container.h
 do
@@ -4588,20 +4648,15 @@ fi
 
 done
 
-    CPPFLAGS=${oldCPPFLAGS}
-
     if test "${net_snmp_container_bug}" = "yes" ; then
-    echo "-------------------------------------------------------------   "
-    { echo "$as_me:$LINENO: WARNING: You should apply the patch xorp/mibs/container.h.patch" >&5
-echo "$as_me: WARNING: You should apply the patch xorp/mibs/container.h.patch" >&2;}
-    echo -n "To do that, copy that file to "
-    echo -n `net-snmp-config --prefix`
-    echo "/include/net-snmp/library"
-    echo "and execute (as root) command 'patch < container.h.patch'"
-    echo "-------------------------------------------------------------   "
+	{ echo "$as_me:$LINENO: WARNING: File <net-snmp/library/container.h> does not appear usable" >&5
+echo "$as_me: WARNING: File <net-snmp/library/container.h> does not appear usable" >&2;}
+	snmpd_valid=no
+	break
     fi
     break
 done
+CPPFLAGS=${oldCPPFLAGS}
 
 if test "${snmpd_valid}" = "yes" ; then
     MIBS="mibs"
