Added a compilation check to config/acipv6.m4 to test whether the IPv6 stack supports IPv6 multicast and IPv6 multicast routing. The new #define names are:
#HAVE_IPV6_MULTICAST
#HAVE_IPV6_MULTICAST_ROUTING

Currently, those new #define names are not used yet.
Theoretically, only the FEA/MFEA should use them.


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@2171 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -7450,6 +7450,139 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 fi
 
+echo "$as_me:$LINENO: checking whether the system IPv6 stack supports IPv6 multicast" >&5
+echo $ECHO_N "checking whether the system IPv6 stack supports IPv6 multicast... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <sys/types.h>
+#include <netinet/in.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+int dummy = 0;
+
+/* Dummy integer values that must be defined in some of the header files */
+dummy += IPV6_MULTICAST_HOPS;
+dummy += IPV6_MULTICAST_LOOP;
+dummy += IPV6_MULTICAST_IF;
+dummy += IPV6_JOIN_GROUP;
+dummy += IPV6_LEAVE_GROUP;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IPV6_MULTICAST 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+echo "$as_me:$LINENO: checking whether the system IPv6 stack supports IPv6 multicast routing" >&5
+echo $ECHO_N "checking whether the system IPv6 stack supports IPv6 multicast routing... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <net/if.h>
+#include <net/if_var.h>
+#include <netinet/in.h>
+#include <netinet/in_var.h>
+#include <netinet6/ip6_mroute.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+int dummy = 0;
+
+/* Dummy values that must be defined in some of the header files */
+dummy += IPPROTO_ICMPV6;
+dummy += MRT6_INIT;
+dummy += MRT6_ADD_MIF;
+dummy += MRT6_DEL_MIF;
+dummy += MRT6_ADD_MFC;
+dummy += MRT6_DEL_MFC;
+dummy += MRT6MSG_NOCACHE;
+dummy += MRT6MSG_WRONGMIF;
+dummy += MRT6MSG_WHOLEPKT;
+
+#ifndef SIOCGETSGCNT_IN6
+#error "Missing SIOCGETSGCNT_IN6"
+#endif
+#ifndef SIOCGETMIFCNT_IN6
+#error "Missing SIOCGETMIFCNT_IN6"
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IPV6_MULTICAST_ROUTING 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
 
 echo "$as_me:$LINENO: checking for post-RFC2292 IPv6 advanced API" >&5
 echo $ECHO_N "checking for post-RFC2292 IPv6 advanced API... $ECHO_C" >&6
