Add a check whether netinet6/nd6.h is C++ friendly, and define HAVE_BROKEN_CXX_NETINET6_ND6_H if not.
git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@4172 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -7739,6 +7739,7 @@ fi
 if test "${ipv6}" = "yes"; then
 
 
+
 echo "$as_me:$LINENO: checking whether the system IPv6 stack implementation is reasonable" >&5
 echo $ECHO_N "checking whether the system IPv6 stack implementation is reasonable... $ECHO_C" >&6
 ipv6=no
@@ -7819,6 +7820,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 fi
 
+
 ipv6_multicast=no
 if test "${ipv6}" = "yes"; then
   echo "$as_me:$LINENO: checking whether the system IPv6 stack supports IPv6 multicast" >&5
@@ -7881,6 +7883,7 @@ echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 fi
+
 
 ipv6_multicast_routing=no
 if test "${ipv6_multicast}" = "yes"; then
@@ -8183,6 +8186,7 @@ fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 fi
 
+
 echo "$as_me:$LINENO: checking for post-RFC2292 IPv6 advanced API" >&5
 echo $ECHO_N "checking for post-RFC2292 IPv6 advanced API... $ECHO_C" >&6
 
@@ -8249,6 +8253,7 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
+
 pv6type=unknown
 echo "$as_me:$LINENO: checking IPv6 stack type" >&5
 echo $ECHO_N "checking IPv6 stack type... $ECHO_C" >&6
@@ -8282,6 +8287,7 @@ rm -f conftest*
 done
 echo "$as_me:$LINENO: result: $ipv6type" >&5
 echo "${ECHO_T}$ipv6type" >&6
+
 
 
 
@@ -8402,6 +8408,194 @@ fi
 done
 
 
+if test "${ac_cv_header_netinet6_nd6_h}" = "yes"; then
+  if test "${ac_cv_header_net_if_var_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for net/if_var.h" >&5
+echo $ECHO_N "checking for net/if_var.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_if_var_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_if_var_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_if_var_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking net/if_var.h usability" >&5
+echo $ECHO_N "checking net/if_var.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <net/if_var.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking net/if_var.h presence" >&5
+echo $ECHO_N "checking net/if_var.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <net/if_var.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: net/if_var.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: net/if_var.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: net/if_var.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/if_var.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for net/if_var.h" >&5
+echo $ECHO_N "checking for net/if_var.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_if_var_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_net_if_var_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_if_var_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_if_var_h" >&6
+
+fi
+if test $ac_cv_header_net_if_var_h = yes; then
+  test_net_if_var_h="#include <net/if_var.h>"
+else
+  test_net_if_var_h=""
+fi
+
+
+
+  test_have_broken_cxx_netinet6_nd6_h_header_files="
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <net/if.h>
+${test_net_if_var_h}
+#include <netinet/in.h>
+#include <netinet/in_var.h>
+// XXX: a hack needed if <netinet6/nd6.h> is not C++ friendly
+// #define prf_ra in6_prflags::prf_ra
+#include <netinet6/nd6.h>
+"
+
+  echo "$as_me:$LINENO: checking whether netinet6/nd6.h is C++ friendly" >&5
+echo $ECHO_N "checking whether netinet6/nd6.h is C++ friendly... $ECHO_C" >&6
+
+
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+${test_have_broken_cxx_netinet6_nd6_h_header_files}
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+size_t size = sizeof(struct in6_prflags);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BROKEN_CXX_NETINET6_ND6_H 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+fi
 
 
 echo "$as_me:$LINENO: checking whether struct sockaddr_in6 has a sin6_len field" >&5
