Add check that "net-snmp-config --cflags" gives sane flags.
git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@2722 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -4433,9 +4433,94 @@ echo "${ECHO_T}no" >&6
     fi
 fi
 
-if test "${net_snmp_found}" = "true";  then
+while test "${net_snmp_found}" = "true"; do
+    NETSNMPCFLAGS=`net-snmp-config --cflags`
+    # Darwin 7.0.0 / OS X 10.3 on ppc gives ppc and i386 arch flags which
+    # the default compiler cannot compile.
+      ac_safe=`echo "${NETSNMPCFLAGS}" | sed 'y%./+- %__p__%'`
+
+
+  _save_flags="$CFLAGS"
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  CFLAGS="$CFLAGS ${NETSNMPCFLAGS}"
+  echo "$as_me:$LINENO: checking whether C compiler supports flag \"${NETSNMPCFLAGS}\"" >&5
+echo $ECHO_N "checking whether C compiler supports flag \"${NETSNMPCFLAGS}\"... $ECHO_C" >&6
+  if eval "test \"\${ac_cv_prog_c_compiler_$ac_safe+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+return (0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "ac_cv_prog_c_compiler_$ac_safe=yes"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "ac_cv_prog_c_compiler_$ac_safe=no"
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+  CFLAGS="$_save_flags"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if eval "test \"`echo '$ac_cv_prog_c_compiler_'$ac_safe`\" = yes"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    :
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    snmpd_valid=no
+  fi
+
+    if test "${snmpd_valid}" = "no" ; then
+	echo "-------------------------------------------------------------   "
+	echo "'net-snmp-config --cflags' gave invalid invalid cflags!         "
+	echo "-------------------------------------------------------------   "
+	break
+    fi
+
     oldCPPFLAGS=${CPPFLAGS}
-    CPPFLAGS=`net-snmp-config --cflags`
+    CPPFLAGS=${NETSNMPCFLAGS}
 
 for ac_header in net-snmp/library/container.h
 do
@@ -4502,7 +4587,8 @@ echo "$as_me: WARNING: You should apply the patch xorp/mibs/container.h.patch" >
     echo "and execute (as root) command 'patch < container.h.patch'"
     echo "-------------------------------------------------------------   "
     fi
-fi
+    break
+done
 
 if test "${snmpd_valid}" = "yes" ; then
     MIBS="mibs"
