Add "./configure" support for DragonFlyBSD (http://www.dragonflybsd.org):
* Conditionally define HOST_OS_DRAGONFLYBSD if the OS is DragonFlyBSD.

* When checking for <netinet/ip_mroute.h>, check for
  <net/ip_mroute/ip_mroute.h> as well.
  Apparently, DragonFlyBSD (as per version 1.4) has moved
  <netinet/ip_mroute.h> to <net/ip_mroute/ip_mroute.h>. Hopefully,
  in the future it will be back to its appropriate location.


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@8494 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -1794,6 +1794,18 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
     ;;
+    dragonfly* )
+
+cat >>confdefs.h <<\_ACEOF
+#define HOST_OS_DRAGONFLYBSD 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HOST_OS_NAME "DragonFlyBSD"
+_ACEOF
+
+    ;;
     freebsd* )
 
 cat >>confdefs.h <<\_ACEOF
@@ -4215,7 +4227,7 @@ test x"$silent" = xyes && libtool_flags="$libtool_flags --silent"
 case "$lt_target" in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4218 "configure"' > conftest.$ac_ext
+  echo '#line 4230 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6995,6 +7007,120 @@ done
 
 
 for ac_header in netinet/igmp.h netinet/ip_mroute.h netinet/pim.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+
+for ac_header in net/ip_mroute/ip_mroute.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -12494,6 +12620,114 @@ else
 fi
 
 
+if test "${ac_cv_header_net_ip_mroute_ip_mroute_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for net/ip_mroute/ip_mroute.h" >&5
+echo $ECHO_N "checking for net/ip_mroute/ip_mroute.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_ip_mroute_ip_mroute_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_ip_mroute_ip_mroute_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_ip_mroute_ip_mroute_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking net/ip_mroute/ip_mroute.h usability" >&5
+echo $ECHO_N "checking net/ip_mroute/ip_mroute.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <net/ip_mroute/ip_mroute.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking net/ip_mroute/ip_mroute.h presence" >&5
+echo $ECHO_N "checking net/ip_mroute/ip_mroute.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <net/ip_mroute/ip_mroute.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for net/ip_mroute/ip_mroute.h" >&5
+echo $ECHO_N "checking for net/ip_mroute/ip_mroute.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_ip_mroute_ip_mroute_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_net_ip_mroute_ip_mroute_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_ip_mroute_ip_mroute_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_ip_mroute_ip_mroute_h" >&6
+
+fi
+if test $ac_cv_header_net_ip_mroute_ip_mroute_h = yes; then
+  test_net_ip_mroute_ip_mroute_h="#include <net/ip_mroute/ip_mroute.h>"
+else
+  test_net_ip_mroute_ip_mroute_h=""
+fi
+
+
 if test "${ac_cv_header_linux_mroute_h+set}" = set; then
   echo "$as_me:$LINENO: checking for linux/mroute.h" >&5
 echo $ECHO_N "checking for linux/mroute.h... $ECHO_C" >&6
@@ -12635,6 +12869,7 @@ ${test_net_route_h}
 #include <netinet/in.h>
 ${test_netinet_in_var_h}
 ${test_netinet_ip_mroute_h}
+${test_net_ip_mroute_ip_mroute_h}
 ${test_linux_mroute_h}
 ${test_linux_mroute_h_missing_defines}
 "
@@ -14147,13 +14382,240 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+if test "${ac_cv_header_netinet_ip_mroute_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for netinet/ip_mroute.h" >&5
+echo $ECHO_N "checking for netinet/ip_mroute.h... $ECHO_C" >&6
+if test "${ac_cv_header_netinet_ip_mroute_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_netinet_ip_mroute_h" >&5
+echo "${ECHO_T}$ac_cv_header_netinet_ip_mroute_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking netinet/ip_mroute.h usability" >&5
+echo $ECHO_N "checking netinet/ip_mroute.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <netinet/ip_mroute.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking netinet/ip_mroute.h presence" >&5
+echo $ECHO_N "checking netinet/ip_mroute.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <netinet/ip_mroute.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: netinet/ip_mroute.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: netinet/ip_mroute.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netinet/ip_mroute.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: netinet/ip_mroute.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: netinet/ip_mroute.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: netinet/ip_mroute.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netinet/ip_mroute.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: netinet/ip_mroute.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netinet/ip_mroute.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: netinet/ip_mroute.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for netinet/ip_mroute.h" >&5
+echo $ECHO_N "checking for netinet/ip_mroute.h... $ECHO_C" >&6
+if test "${ac_cv_header_netinet_ip_mroute_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_netinet_ip_mroute_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_netinet_ip_mroute_h" >&5
+echo "${ECHO_T}$ac_cv_header_netinet_ip_mroute_h" >&6
+
+fi
+if test $ac_cv_header_netinet_ip_mroute_h = yes; then
+  test_netinet_ip_mroute_h="
+/*
+ * XXX: On NetBSD and OpenBSD the definition of 'struct igmpmsg'
+ * and IGMPMSG_* is wrapped inside #ifdef _KERNEL hence we need
+ * to define _KERNEL before including <netinet/ip_mroute.h>.
+ */
+#define _KERNEL
+#include <netinet/ip_mroute.h>
+#undef _KERNEL
+"
+else
+  test_netinet_ip_mroute_h=""
+fi
+
+
+if test "${ac_cv_header_net_ip_mroute_ip_mroute_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for net/ip_mroute/ip_mroute.h" >&5
+echo $ECHO_N "checking for net/ip_mroute/ip_mroute.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_ip_mroute_ip_mroute_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_ip_mroute_ip_mroute_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_ip_mroute_ip_mroute_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking net/ip_mroute/ip_mroute.h usability" >&5
+echo $ECHO_N "checking net/ip_mroute/ip_mroute.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <net/ip_mroute/ip_mroute.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking net/ip_mroute/ip_mroute.h presence" >&5
+echo $ECHO_N "checking net/ip_mroute/ip_mroute.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <net/ip_mroute/ip_mroute.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: net/ip_mroute/ip_mroute.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for net/ip_mroute/ip_mroute.h" >&5
+echo $ECHO_N "checking for net/ip_mroute/ip_mroute.h... $ECHO_C" >&6
+if test "${ac_cv_header_net_ip_mroute_ip_mroute_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_net_ip_mroute_ip_mroute_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_net_ip_mroute_ip_mroute_h" >&5
+echo "${ECHO_T}$ac_cv_header_net_ip_mroute_ip_mroute_h" >&6
+
+fi
+if test $ac_cv_header_net_ip_mroute_ip_mroute_h = yes; then
+  test_net_ip_mroute_ip_mroute_h="#include <net/ip_mroute/ip_mroute.h>"
+else
+  test_net_ip_mroute_ip_mroute_h=""
+fi
+
+
+
 test_mfcctl2_headers="
 #include <sys/types.h>
 #include <sys/time.h>
 #include <sys/socket.h>
 #include <net/route.h>
 #include <netinet/in.h>
-#include <netinet/ip_mroute.h>
+${test_netinet_ip_mroute_h}
+${test_net_ip_mroute_ip_mroute_h}
 "
 
 echo "$as_me:$LINENO: checking for struct mfcctl2" >&5
