Added a check whether struct ifreq (in net/if.h) contains field ifr_ifindex. This check is needed because in FreeBSD-5.x the field with the interface index in struct ifreq is called ifr_index, but in Linux the field is called ifr_ifindex.
git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@2314 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/configure b/trunk/xorp/configure
--- a/trunk/xorp/configure
+++ b/trunk/xorp/configure
@@ -1654,6 +1654,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
+
 cat >>confdefs.h <<_ACEOF
 #define XORP_INSTALL_ROOT "${ac_default_prefix}"
 _ACEOF
@@ -6632,6 +6633,61 @@ echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SUN_LEN 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+
+echo "$as_me:$LINENO: checking whether struct ifreq has field ifr_ifindex" >&5
+echo $ECHO_N "checking whether struct ifreq has field ifr_ifindex... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <net/if.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+static struct ifreq ifreq;
+int i = sizeof(ifreq.ifr_ifindex);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IFR_IFINDEX 1
 _ACEOF
 
 else
