Catch all unrecognized options and print an error before exiting.
git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@3266 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/pim/rconfig_pim b/trunk/xorp/pim/rconfig_pim
--- a/trunk/xorp/pim/rconfig_pim
+++ b/trunk/xorp/pim/rconfig_pim
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #
-# $XORP: xorp/pim/rconfig_pim,v 1.1.1.1 2002/12/11 23:56:12 hodson Exp $
+# $XORP: xorp/pim/rconfig_pim,v 1.2 2004/02/27 00:20:18 pavlin Exp $
 #
 
 #
@@ -36,6 +36,12 @@ if [ $# -gt 0 ] ; then
 		-h)
 			usage;
 			exit 0
+			;;
+		-*)
+			# XXX: all other options are invalid
+			echo "Invalid option ${1}"
+			usage;
+			exit 1
 			;;
 		*)
 			;;
