Resolve two long-standing bugs in the XORP SNMP agent build.
1. Forcibly disable the use of inlining when building
   code against net-snmp includes and libraries. The net-snmp
   headers erroneously declare certain functions (such as
   netsnmp_request_get_list_data) as being inline, when they
   are not defined within the same translation unit, and
   therefore correctly trigger an error in ANSI C++ compilers.

   A special workaround is needed which is dependent on the
   version of net-snmp in use. Versions in the 5.0.x series
   don't support -DNETSNMP_NO_INLINE correctly.

2. Workaround compiler warnings caused by the redefinition of
   preprocessor macros named PACKAGExxx, by forcibly undefining
   the values defined for them by mibs/configure. This is
   achieved by adding -U flags to AM_CPPFLAGS in mibs/Makefile.in.

   These definitions arise because versions of autoconf newer than
   2.52 try to define these macros when the AC_INIT macro is called.
   However, these macros have already been defined in net-snmp's
   include file namespace. This is an obvious net-snmp bug.

   It is still necessary to include fixconfigs.h to undefine
   net-snmp's subsequent definitions of these macros. This poses
   no problem as the XORP SNMP agent code does not reference them.

Merge from:	Perforce
Bugzilla ID:	89


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@5296 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/mibs/configure b/trunk/xorp/mibs/configure
--- a/trunk/xorp/mibs/configure
+++ b/trunk/xorp/mibs/configure
@@ -5068,6 +5068,17 @@ else
 	    ac_cv_net_snmp_usable=no
 	    snmpd="skip_check"
 	fi
+	if test "${net_snmp_maj}" -eq "5" -a "${net_snmp_min}" -le "1"; then
+	   { echo "$as_me:$LINENO: WARNING: net-snmp version has broken inlining defines" >&5
+echo "$as_me: WARNING: net-snmp version has broken inlining defines" >&2;}
+	   cat >>confdefs.h <<\_ACEOF
+#define HAVE_BROKEN_NETSNMP_INLINE 1
+_ACEOF
+
+	   ac_cv_net_snmp_broken_inline=yes
+	else
+	   ac_cv_net_snmp_broken_inline=no
+	fi
 
 fi
 echo "$as_me:$LINENO: result: $ac_cv_net_snmp_usable" >&5
@@ -5245,6 +5256,174 @@ fi
 oldCPPFLAGS=${CPPFLAGS}
 while test "${net_snmp_found}" = "true"; do
     NETSNMPCFLAGS=`net-snmp-config --cflags`
+
+    # Some versions of net-snmp are broken with respect to the use of
+    # the 'inline' keyword and various C++ compilers, so can't be
+    # explicitly told not to inline.
+    # It is OK to say -DNETSNMP_NO_INLINE to net-snmp >= 5.2.1,
+    # but not < 5.1.0.
+    if test "${ac_cv_net_snmp_broken_inline}" = "no"; then
+	NETSNMPCFLAGS="${NETSNMPCFLAGS} -DNETSNMP_NO_INLINE"
+	for ac_flag in "-DNETSNMP_NO_INLINE"
+  do
+      ac_safe=`echo "$ac_flag" | sed 'y%./+- %__p__%'`
+
+
+  _save_flags="$CFLAGS"
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  CFLAGS="$CFLAGS $ac_flag"
+  echo "$as_me:$LINENO: checking whether C compiler supports flag \"$ac_flag\"" >&5
+echo $ECHO_N "checking whether C compiler supports flag \"$ac_flag\"... $ECHO_C" >&6
+  if eval "test \"\${ac_cv_prog_c_compiler_$ac_safe+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+return (0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "ac_cv_prog_c_compiler_$ac_safe=yes"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "ac_cv_prog_c_compiler_$ac_safe=no"
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+  CFLAGS="$_save_flags"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if eval "test \"`echo '$ac_cv_prog_c_compiler_'$ac_safe`\" = yes"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    CFLAGS="$CFLAGS $ac_flag"
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+  fi
+
+  done
+
+	for ac_flag in "-DNETSNMP_NO_INLINE"
+  do
+      ac_safe=`echo "$ac_flag" | sed 'y%./+- %__p__%'`
+
+
+  _save_flags="$CXXFLAGS"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  CXXFLAGS="$CXXFLAGS $ac_flag"
+  echo "$as_me:$LINENO: checking whether C++ compiler supports flag \"$ac_flag\"" >&5
+echo $ECHO_N "checking whether C++ compiler supports flag \"$ac_flag\"... $ECHO_C" >&6
+  if eval "test \"\${ac_cv_prog_cxx_compiler_$ac_safe+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+return (0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "ac_cv_prog_cxx_compiler_$ac_safe=yes"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "ac_cv_prog_cxx_compiler_$ac_safe=no"
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+  CXXFLAGS="$_save_flags"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if eval "test \"`echo '$ac_cv_prog_cxx_compiler_'$ac_safe`\" = yes"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    CXXFLAGS="$CXXFLAGS $ac_flag"
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+  fi
+
+  done
+
+    fi
+
     # Darwin 7.0.0 / OS X 10.3 on ppc gives ppc and i386 arch flags which
     # the default compiler cannot compile.
       ac_safe=`echo "${NETSNMPCFLAGS}" | sed 'y%./+- %__p__%'`
