Return an error if the user runs ./configure --with-snmp but net-snmp is not installed.
This fixes Bugzilla entry 838.

Bugzilla URL:	http://bugzilla.xorp.org/bugzilla/show_bug.cgi?id=838
Approved by:	Syed Khalid


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@11224 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/mibs/configure b/trunk/xorp/mibs/configure
--- a/trunk/xorp/mibs/configure
+++ b/trunk/xorp/mibs/configure
@@ -20518,8 +20518,11 @@ _ACEOF
 
     fi
 elif test "${net_snmp_found}" = "false"; then
-    { echo "$as_me:$LINENO: WARNING: Net-SNMP not found! MIB modules will not be built" >&5
-echo "$as_me: WARNING: Net-SNMP not found! MIB modules will not be built" >&2;}
+    # XXX: If the user explicitly specified to build SNMP, it is a critical
+    # error if SNMP is not found.
+    { { echo "$as_me:$LINENO: error: Net-SNMP not found! MIB modules will not be built" >&5
+echo "$as_me: error: Net-SNMP not found! MIB modules will not be built" >&2;}
+   { (exit 1); exit 1; }; }
     snmpd="skip_check"
 fi
 
@@ -21151,8 +21154,11 @@ CPPFLAGS=${oldCPPFLAGS}
 if test "${snmpd_valid}" = "yes" ; then
     MIBS="mibs"
 else
-    { echo "$as_me:$LINENO: WARNING: XORP MIBs will not be built" >&5
-echo "$as_me: WARNING: XORP MIBs will not be built" >&2;}
+    # XXX: If the user explicitly specified to build SNMP, it is a critical
+    # error if SNMP is not found.
+    { { echo "$as_me:$LINENO: error: XORP MIBs will not be built" >&5
+echo "$as_me: error: XORP MIBs will not be built" >&2;}
+   { (exit 1); exit 1; }; }
     MIBS=""
 fi
 
