Add test suite to ensure that rtrmgr template files in CVS parse correctly and that the XRLs in the template files match the XRLs in the XIF files.
git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@427 26435e26-4b25-483a-942d-477236992e84

diff --git a/trunk/xorp/rtrmgr/Makefile.in b/trunk/xorp/rtrmgr/Makefile.in
--- a/trunk/xorp/rtrmgr/Makefile.in
+++ b/trunk/xorp/rtrmgr/Makefile.in
@@ -81,20 +81,30 @@ RIP = @RIP@
 RIP_OS = @RIP_OS@
 
 bin_PROGRAMS = rtrmgr xorpsh
+#bin_PROGRAMS	 = rtrmgr
+
+# -- Test Programs
+#bin_PROGRAMS	+=
+
+TESTS = test_templates
+
+noinst_PROGRAMS = $(TESTS)
 EXTRA_DIST = Notes config.boot config.template fea.boot
 
 # -- Libraries and library flags to link the binary programs
 LDFLAGS = -all-static
 LDADD = $(top_builddir)/libxipc/libxipc.a $(top_builddir)/libxorp/libxorp.a
-rtrmgr_SOURCES = rtrmgr_module.h md5.h version.h y.tplt_tab.cc lex.tplt.cc y.boot_tab.cc lex.boot.cc main_rtrmgr.cc template_tree.cc template_tree_node.cc template_commands.cc conf_tree_node.cc conf_tree.cc master_conf_tree_node.cc master_conf_tree.cc module_manager.cc xorp_client.cc xrldb.cc split.cc userdb.cc xrl_rtrmgr_interface.cc randomness.cc unexpanded_xrl.cc version.h
+rtrmgr_SOURCES = rtrmgr_module.h md5.h version.h y.tplt_tab.cc lex.tplt.cc y.boot_tab.cc lex.boot.cc main_rtrmgr.cc template_tree.cc template_tree_node.cc template_commands.cc conf_tree_node.cc conf_tree.cc master_conf_tree_node.cc master_conf_tree.cc module_manager.cc xorp_client.cc xrldb.cc split.cc userdb.cc xrl_rtrmgr_interface.cc randomness.cc unexpanded_xrl.cc
 rtrmgr_LDADD = $(LDADD)  $(top_builddir)/xrl/targets/librtrmgrbase.a  $(top_builddir)/xrl/interfaces/librtrmgr_clientxif.a 
 #unexpanded_xrl shouldn't really be needed
-xorpsh_SOURCES = rtrmgr_module.h xorpsh_main.cc y.tplt_tab.cc lex.tplt.cc y.boot_tab.cc lex.boot.cc y.opcmd_tab.cc lex.opcmd.cc template_tree.cc template_tree_node.cc template_commands.cc conf_tree_node.cc slave_conf_tree_node.cc conf_tree.cc slave_module_manager.cc  slave_conf_tree.cc xorp_client.cc xrldb.cc cli.cc command_tree.cc op_commands.cc popen.cc split.cc xrl_xorpsh_interface.cc unexpanded_xrl.cc
+xorpsh_SOURCES = rtrmgr_module.h version.h xorpsh_main.cc y.tplt_tab.cc lex.tplt.cc y.boot_tab.cc lex.boot.cc y.opcmd_tab.cc lex.opcmd.cc template_tree.cc template_tree_node.cc template_commands.cc conf_tree_node.cc slave_conf_tree_node.cc conf_tree.cc slave_module_manager.cc  slave_conf_tree.cc xorp_client.cc xrldb.cc cli.cc command_tree.cc op_commands.cc popen.cc split.cc xrl_xorpsh_interface.cc unexpanded_xrl.cc
 xorpsh_LDADD = $(top_builddir)/cli/libcli.a $(top_builddir)/libproto/libproto.a $(top_builddir)/cli/libtecla/libtecla.a -lcurses $(top_builddir)/libcomm/libcomm.a $(top_builddir)/xrl/interfaces/librtrmgrxif.a $(top_builddir)/xrl/targets/libxorpshbase.a $(LDADD)
+test_templates_SOURCES = test_templates.cc y.tplt_tab.cc lex.tplt.cc template_tree.cc template_tree_node.cc template_commands.cc xrldb.cc unexpanded_xrl.cc conf_tree_node.cc command_tree.cc xorp_client.cc module_manager.cc split.cc
+test_templates_LDADD = $(LDADD)
 mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
 CONFIG_HEADER = ../config.h
 CONFIG_CLEAN_FILES = 
-PROGRAMS =  $(bin_PROGRAMS)
+PROGRAMS =  $(bin_PROGRAMS) $(noinst_PROGRAMS)
 
 
 DEFS = @DEFS@ -I. -I$(srcdir) -I..
@@ -124,6 +134,13 @@ $(top_builddir)/xrl/interfaces/librtrmgrxif.a \
 $(top_builddir)/xrl/targets/libxorpshbase.a \
 $(top_builddir)/libxipc/libxipc.a $(top_builddir)/libxorp/libxorp.a
 xorpsh_LDFLAGS = 
+test_templates_OBJECTS =  test_templates.o y.tplt_tab.o lex.tplt.o \
+template_tree.o template_tree_node.o template_commands.o xrldb.o \
+unexpanded_xrl.o conf_tree_node.o command_tree.o xorp_client.o \
+module_manager.o split.o
+test_templates_DEPENDENCIES =  $(top_builddir)/libxipc/libxipc.a \
+$(top_builddir)/libxorp/libxorp.a
+test_templates_LDFLAGS = 
 CXXFLAGS = @CXXFLAGS@
 CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
 CXXLD = $(CXX)
@@ -149,12 +166,13 @@ DEP_FILES =  .deps/cli.P .deps/command_tree.P .deps/conf_tree.P \
 .deps/op_commands.P .deps/popen.P .deps/randomness.P \
 .deps/slave_conf_tree.P .deps/slave_conf_tree_node.P \
 .deps/slave_module_manager.P .deps/split.P .deps/template_commands.P \
-.deps/template_tree.P .deps/template_tree_node.P .deps/unexpanded_xrl.P \
-.deps/userdb.P .deps/xorp_client.P .deps/xorpsh_main.P \
-.deps/xrl_rtrmgr_interface.P .deps/xrl_xorpsh_interface.P .deps/xrldb.P \
-.deps/y.boot_tab.P .deps/y.opcmd_tab.P .deps/y.tplt_tab.P
-SOURCES = $(rtrmgr_SOURCES) $(xorpsh_SOURCES)
-OBJECTS = $(rtrmgr_OBJECTS) $(xorpsh_OBJECTS)
+.deps/template_tree.P .deps/template_tree_node.P .deps/test_templates.P \
+.deps/unexpanded_xrl.P .deps/userdb.P .deps/xorp_client.P \
+.deps/xorpsh_main.P .deps/xrl_rtrmgr_interface.P \
+.deps/xrl_xorpsh_interface.P .deps/xrldb.P .deps/y.boot_tab.P \
+.deps/y.opcmd_tab.P .deps/y.tplt_tab.P
+SOURCES = $(rtrmgr_SOURCES) $(xorpsh_SOURCES) $(test_templates_SOURCES)
+OBJECTS = $(rtrmgr_OBJECTS) $(xorpsh_OBJECTS) $(test_templates_OBJECTS)
 
 all: all-redirect
 .SUFFIXES:
@@ -192,6 +210,15 @@ uninstall-binPROGRAMS:
 	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
 	done
 
+mostlyclean-noinstPROGRAMS:
+
+clean-noinstPROGRAMS:
+	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
+
+distclean-noinstPROGRAMS:
+
+maintainer-clean-noinstPROGRAMS:
+
 .s.o:
 	$(COMPILE) -c $<
 
@@ -215,6 +242,10 @@ rtrmgr: $(rtrmgr_OBJECTS) $(rtrmgr_DEPENDENCIES)
 xorpsh: $(xorpsh_OBJECTS) $(xorpsh_DEPENDENCIES)
 	@rm -f xorpsh
 	$(CXXLINK) $(xorpsh_LDFLAGS) $(xorpsh_OBJECTS) $(xorpsh_LDADD) $(LIBS)
+
+test_templates: $(test_templates_OBJECTS) $(test_templates_DEPENDENCIES)
+	@rm -f test_templates
+	$(CXXLINK) $(test_templates_LDFLAGS) $(test_templates_OBJECTS) $(test_templates_LDADD) $(LIBS)
 .cc.o:
 	$(CXXCOMPILE) -c $<
 
@@ -318,11 +349,37 @@ maintainer-clean-depend:
 	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
 	    >> .deps/$(*F).P; \
 	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -354,22 +411,25 @@ distclean-generic:
 	-rm -f config.cache config.log stamp-h stamp-h[0-9]*
 
 maintainer-clean-generic:
-mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
-		mostlyclean-tags mostlyclean-depend mostlyclean-generic
+mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-noinstPROGRAMS \
+		mostlyclean-compile mostlyclean-tags mostlyclean-depend \
+		mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
-clean-am:  clean-binPROGRAMS clean-compile clean-tags clean-depend \
-		clean-generic mostlyclean-am
+clean-am:  clean-binPROGRAMS clean-noinstPROGRAMS clean-compile \
+		clean-tags clean-depend clean-generic mostlyclean-am
 
 clean: clean-am
 
-distclean-am:  distclean-binPROGRAMS distclean-compile distclean-tags \
-		distclean-depend distclean-generic clean-am
+distclean-am:  distclean-binPROGRAMS distclean-noinstPROGRAMS \
+		distclean-compile distclean-tags distclean-depend \
+		distclean-generic clean-am
 
 distclean: distclean-am
 
 maintainer-clean-am:  maintainer-clean-binPROGRAMS \
+		maintainer-clean-noinstPROGRAMS \
 		maintainer-clean-compile maintainer-clean-tags \
 		maintainer-clean-depend maintainer-clean-generic \
 		distclean-am
@@ -380,13 +440,15 @@ maintainer-clean: maintainer-clean-am
 
 .PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
 maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
+mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
+clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
 mostlyclean-compile distclean-compile clean-compile \
 maintainer-clean-compile tags mostlyclean-tags distclean-tags \
 clean-tags maintainer-clean-tags distdir mostlyclean-depend \
-distclean-depend clean-depend maintainer-clean-depend info-am info \
-dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
-install-exec install-data-am install-data install-am install \
-uninstall-am uninstall all-redirect all-am all installdirs \
+distclean-depend clean-depend maintainer-clean-depend check-TESTS \
+info-am info dvi-am dvi check check-am installcheck-am installcheck \
+install-exec-am install-exec install-data-am install-data install-am \
+install uninstall-am uninstall all-redirect all-am all installdirs \
 mostlyclean-generic distclean-generic clean-generic \
 maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
